"""
Kernel method → IAM action mapping.

Single source of truth shared by:
  lib/akasha/kernel.py   — dispatch routing
  lib/akasha/csl/validator.py — CSL method validation

No imports — this module must remain dependency-free so the validator
can load it without pulling in the full kernel import chain.

Adding a new method: add one entry here.  Kernel dispatch and CSL
validation stay in sync automatically.
"""
from typing import Dict

METHOD_TO_ACTION: Dict[str, str] = {
    # Memory
    "kernel.memory.write": "write",    "write": "write",    "w": "write",
    "kernel.memory.define": "write",   "define": "write",   "def": "write",
    "kernel.memory.read": "read",      "read": "read",      "r": "read",
    "kernel.memory.drop": "drop",      "drop": "drop",      "rm": "drop",
    "kernel.memory.link": "link.create", "link.create": "link.create", "ln": "link.create",
    "link.list": "link.list",
    "link.reinforce": "link.reinforce",
    "meta.set": "meta.set",
    # Aliases
    "kernel.identity.alias": "write",
    "alias": "write", "al": "write",
    "kernel.identity.alias.list": "read",
    "alias.list": "read", "al.ls": "read",
    "kernel.identity.alias.find": "read",
    "alias.find": "read", "al.find": "read",
    # Exploration
    "explore": "explore",
    "network.tree": "network.tree",
    "graph.tree": "read",
    # Dive
    "dive.look": "dive.look", "look": "dive.look",
    "dive.out": "dive.out",  "out": "dive.out",
    # Sets
    "set.add": "write",
    "set.rm": "drop",
    "set.ls": "read",
    "set.clear": "drop",
    "set.op": "write",
    # FieldNote
    "fieldnote.new":    "write",
    "fieldnote.ls":     "read",
    "fieldnote.open":   "read",
    "fieldnote.add":    "write",
    "fieldnote.read":   "read",
    "fieldnote.rm":     "drop",
    "fieldnote.export": "read",
    "fieldnote.import": "write",
    # Notes
    "note.new":       "write",
    "note.add":       "write",
    "note.section":   "write",
    "note.paragraph": "write",
    "note.toc":       "read",
    "note.read":      "read",
    "note.rm":        "drop",
    "note.list":      "read",
    "note.edit":      "write",
    "note.move":      "write",
    "note.undo":      "write",
    "note.redo":      "write",
    "note.restore":   "write",
    "note.rename":    "write",
    "note.ls":        "read",
    "note.open":      "write",
    "note.export":    "read",
    "note.import":    "write",
    "note.clone":     "write",
    # Loom (note model isolated under "loom" namespace)
    "loom.note.new":     "write",
    "loom.note.add":     "write",
    "loom.note.read":    "read",
    "loom.note.rm":      "drop",
    "loom.note.list":    "read",
    "loom.note.edit":    "write",
    "loom.note.move":    "write",
    "loom.note.undo":    "write",
    "loom.note.redo":    "write",
    "loom.note.restore": "write",
    "loom.note.rename":  "write",
    "loom.note.ls":      "read",
    "loom.note.open":    "write",
    "loom.note.export":  "read",
    "loom.note.import":  "write",
    "loom.note.clone":   "write",
    # Associate (assoc — gap detection; fill=yes writes links)
    "kernel.associate":    "write",
    "associate.unwritten": "read",
    # Jataka (dream — hypothetical linking; commit=yes writes tent: links)
    "jataka.dream": "write", "dream": "write",
    # Contexa
    "contexa.fetch": "read",
    "web.search": "read",
    "fetch": "read",
    # Sys
    "sys.onboarding.seed": "write",
    "onto.dump":           "read",
    "onto.export":         "read",
    "onto.status":         "read",
    "onto.pack.list":      "read",
    "onto.pack.enable":    "write",   # handler enforces role:librarian
    "onto.pack.disable":   "write",   # handler enforces role:librarian
    "onto.reload":         "write",   # handler enforces role:librarian
    "onto.reset":          "write",   # handler enforces role:librarian
    "sys.cogito": "status", "cogito": "status",
    "sys.status": "status", "sys.status.full": "status",
    "sys.history": "sys.history",
    "sys.session.close": "status",
    "sys.scope.set":   "status",
    "sys.scope.get":   "status",
    "sys.scope.reset": "status",
    "sys.ls": "read",
    # Log
    "log.new":        "write",
    "log.checkpoint": "write",
    "log.annotate":   "write",
    "log.replay":     "read",
    "log.read":       "read",
    "log.rm":         "drop",
    # Cockpit
    "cockpit.ls":     "read",
    "cockpit.new":    "write",
    "cockpit.open":   "read",
    "cockpit.status": "read",
    "cockpit.lock":   "write",
    "cockpit.tune":   "write",
    "cockpit.beacon": "write",
    "cockpit.wake":   "read",
    "cockpit.rm":     "drop",
    # Whiteboard
    "wb.new":    "status",
    "wb.pin":    "status",
    "wb.unpin":  "status",
    "wb.focus":  "status",
    "wb.ls":     "status",
    "wb.show":   "status",
    "wb.rm":     "status",
    # Cross
    "sys.cross.query": "read",
    "sys.cross.axes":  "read",
    "sys.cross.atom":  "read",
    # Sync
    "sync.push": "sync.push",
    "sync.pull": "sync.pull",
    # JCL
    "job.submit": "job.submit",
    "job.ls":     "read",
    "job.stat":   "read",
    "job.cancel": "drop",
    # Workflow — a stored CSL script run as an orchestrated JCL job.
    # workflow.run submits a job, so it carries the same admin/librarian gate as
    # job.submit; def/ls/get/rm are ordinary graph ops.
    "workflow.def": "write",
    "workflow.run": "job.submit",
    "workflow.ls":  "read",
    "workflow.get": "read",
    "workflow.rm":  "drop",
    # Locale
    "locale.get": "status",
    "locale.set": "status",
    # Record (schema-free)
    "rec.new": "write",
    "rec.set": "write",
    "rec.idx": "write",
    "rec.get": "read",
    "rec.ls":  "read",
    "rec.sum": "read",
    "rec.rm":  "drop",
    # Table (schema-first, CSV/RDB-compatible; rows are rec-compatible atoms)
    "table.new":     "write",
    "table.get":     "read",
    "table.rm":      "drop",
    "table.col.add": "write",
    "table.col.ls":  "read",
    "table.row.add": "write",
    "table.row.get": "read",
    "table.row.rm":  "drop",
    "table.ls":      "read",
    "table.export":  "read",
    "table.import":  "write",
    # Lens (source scanner + concept-model projection engine)
    "lens.scan": "read",
    "lens.cast": "write",
    # CSL
    "csl":         "write",
    "csl.run":     "write",
    "csl.check":   "read",
    "csl.build":   "write",
    # Aggregation
    "agg.new":          "write",
    "agg.open":         "read",
    "agg.ls":           "read",
    "agg.unit.add":     "write",
    "agg.group.add":    "write",
    "agg.measure.add":  "write",
    "agg.analysis.add": "write",
    "agg.hier.add":     "write",
    "agg.list":         "read",
    "agg.rm":           "drop",
    # Presentation
    "pres.new":         "write",
    "pres.open":        "read",
    "pres.ls":          "read",
    "pres.deck.add":    "write",
    "pres.frame.add":   "write",
    "pres.region.add":  "write",
    "pres.node.add":    "write",
    "pres.list":        "read",
    "pres.rm":          "drop",
    # Synthesis
    "synth.new":        "write",
    "synth.open":       "read",
    "synth.ls":         "read",
    "synth.source.add": "write",
    "synth.code.add":   "write",
    "synth.theme.add":  "write",
    "synth.interp.add": "write",
    "synth.claim.add":  "write",
    "synth.thread.new": "write",
    "synth.thread.add": "write",
    "synth.map":        "read",
    "synth.trace":      "read",
    "synth.rm":         "drop",
    # Cast
    "cast.new":           "write",
    "cast.open":          "read",
    "cast.ls":            "read",
    "cast.map":           "read",
    "cast.clone":         "write",
    "cast.rm":            "drop",
    "cast.identity.set":  "write",
    "cast.appear.set":    "write",
    "cast.ability.set":   "write",
    "cast.adorn.add":     "write",
    "cast.skill.add":     "write",
    "cast.possess.add":   "write",
    "cast.pos.set":       "write",
    "cast.emotion.add":   "write",
    "cast.wound.add":     "write",
    "cast.policy.add":    "write",
    "cast.rule.add":      "write",
    "cast.trait.set":     "write",
    "cast.state.set":     "write",
    "cast.mask.add":      "write",
    "cast.secret.add":    "write",
    "cast.output.add":    "write",
    "cast.conflict.add":  "write",
    "cast.shadow.add":    "write",
    "cast.bond.add":      "write",
    "cast.bond.update":   "write",
    "cast.fate.set":      "write",
    "cast.calling.set":   "write",
    "cast.role.set":      "write",
    "cast.myth.set":      "write",
    "cast.arc.add":       "write",
    "cast.react":         "read",
    "cast.diagnose":      "read",
    # World
    "world.new":          "write",
    "world.open":         "read",
    "world.ls":           "read",
    "world.map":          "read",
    "world.rm":           "drop",
    "world.place.add":    "write",
    "world.place.state":  "write",
    "world.object.add":   "write",
    "world.prop.add":     "write",
    "world.collect.add":  "write",
    "world.collect.put":  "write",
    "world.connect":      "write",
    "world.portal.add":   "write",
    "world.law.add":      "write",
    "world.law.change":   "write",
    "world.hidden.add":   "write",
    "world.event":        "write",
    "world.diagnose":     "read",
    # Human (evidence-based actor model)
    "human.new":          "write",
    "human.open":         "write",
    "human.ls":           "read",
    "human.map":          "read",
    "human.rm":           "write",
    "human.name.add":     "write",
    "human.birth.set":    "write",
    "human.death.set":    "write",
    "human.status.set":   "write",
    "human.pseudo.add":   "write",
    "human.assess":       "write",
    "human.estimate":     "write",
    "human.merge.link":   "write",
    "human.merge.confirm":"write",
    "human.alias":        "write",
    "human.dispute":      "write",
    "human.fictionalize": "write",
    "human.bond.add":     "write",
    "human.bond.update":  "write",
    "human.observable":   "read",
    "human.timeline":     "read",
    "human.profile":      "read",
    "human.diagnose":     "read",
    "human.trace":        "read",
    # Country
    "country.new":              "write",
    "country.open":             "write",
    "country.ls":               "read",
    "country.map":              "read",
    "country.rm":               "write",
    "country.name.add":         "write",
    "country.territory.add":    "write",
    "country.capital.set":      "write",
    "country.gov.set":          "write",
    "country.pop.set":          "write",
    "country.econ.add":         "write",
    "country.sovereignty.set":  "write",
    "country.claim.add":        "write",
    "country.admin.add":        "write",
    "country.law.add":          "write",
    "country.law.change":       "write",
    "country.event.add":        "write",
    "country.corr.link":        "write",
    "country.profile":          "read",
    "country.timeline":         "read",
    "country.observable":       "read",
    "country.diagnose":         "read",
    "country.trace":            "read",
    # Map
    "map.new":              "write",
    "map.open":             "write",
    "map.ls":               "read",
    "map.map":              "read",
    "map.show":             "read",
    "map.rm":               "write",
    "map.edition.add":      "write",
    "map.feature.add":      "write",
    "map.geometry.add":     "write",
    "map.label.add":        "write",
    "map.projection.add":   "write",
    "map.ground":           "write",
    "map.snapshot.add":     "write",
    "map.transition.add":   "write",
    "map.history":          "read",
    "map.timeview":         "read",
    "map.time.rebuild":     "write",
    "map.eval":             "write",
    "map.diagnose":         "read",
    "map.trace":            "read",
    # Correspondence
    "corr.new":          "write",
    "corr.open":         "write",
    "corr.ls":           "read",
    "corr.map":          "read",
    "corr.rm":           "write",
    "corr.system.add":   "write",
    "corr.source.add":   "write",
    "corr.source.eval":  "write",
    "corr.link.add":     "write",
    "corr.link.infer":   "write",
    "corr.project.add":  "write",
    "corr.eval.add":     "write",
    "corr.dispute.add":  "write",
    "corr.trace":        "read",
    "corr.diagnose":     "read",
    # Fact
    "fact.new":         "write",
    "fact.open":        "write",
    "fact.ls":          "read",
    "fact.map":         "read",
    "fact.rm":          "write",
    "fact.source.add":  "write",
    "fact.source.eval": "write",
    "fact.add":         "write",
    "fact.claim":       "write",
    "fact.absent":      "write",
    "fact.infer":       "write",
    "fact.set.new":     "write",
    "fact.set.add":     "write",
    "fact.entity.link": "write",
    "fact.diagnose":    "read",
    "fact.trace":       "read",
    # Curation
    "curation.new":            "write",
    "curation.open":           "read",
    "curation.ls":             "read",
    "curation.map":            "read",
    "curation.rm":             "drop",
    "curation.premise.add":    "write",
    "curation.input.add":      "write",
    "curation.view.run":       "write",
    "curation.fold.add":       "write",
    "curation.conclusion.add": "write",
    "curation.dispute.add":    "write",
    "curation.trace":          "read",
    "curation.diagnose":       "read",
    # Intelligence
    "intelligence.new":            "write",
    "intelligence.open":           "read",
    "intelligence.ls":             "read",
    "intelligence.map":            "read",
    "intelligence.rm":             "drop",
    "intelligence.req.add":        "write",
    "intelligence.scan.add":       "write",
    "intelligence.gap.add":        "write",
    "intelligence.task.add":       "write",
    "intelligence.assess.add":     "write",
    "intelligence.estimate.add":   "write",
    "intelligence.option.add":     "write",
    "intelligence.recommend.add":  "write",
    "intelligence.decision.add":   "write",
    "intelligence.dispute.add":    "write",
    "intelligence.cycle":          "read",
    "intelligence.trace":          "read",
    "intelligence.diagnose":       "read",
    # Harmonia — Soma
    "soma.new":    "write",
    "soma.equip":  "write",
    "soma.status": "read",
    "soma.repair": "write",
    # Harmonia — Engram
    "engram.new":      "write",
    "engram.talk":     "write",
    "engram.bond":     "write",
    "engram.metaphor": "write",
    # Harmonia — Operator
    "operator.clash": "write",
    # Harmonia — Eidolon
    "eidolon.new":  "write",
    "eidolon.open": "write",
    "eidolon.ls":   "read",
    "eidolon.link": "write",
    "eidolon.move": "write",
    "eidolon.map":  "read",
    "eidolon.rm":   "write",
    # Session Instance Layer
    "instance.mount":   "write",
    "instance.join":    "write",
    "instance.focus":   "write",
    "instance.blur":    "write",
    "instance.bind":    "write",
    "instance.ls":      "read",
    "instance.unmount": "write",
    # Guest session (pre-auth, no IAM check)
    "session.guest.create":  "session.guest",
    "session.guest.extend":  "session.guest",
    # Session context (all authenticated roles incl. GUEST)
    "session.context.set": "read",
    "session.context.get": "read",
    # Thesaurus concept model (public read / authenticated write)
    "thesaurus.shelf.score":    "read",
    "thesaurus.shelf.list":     "read",
    "thesaurus.shelf.link":     "write",
    "thesaurus.shelf.link_ext": "write",
    "thesaurus.curation.new":   "write",
    "thesaurus.curation.ls":    "read",
    "thesaurus.curation.atom":  "write",
    "thesaurus.series.new":     "write",
    "thesaurus.series.ls":      "read",
    "thesaurus.series.add":     "write",
    "thesaurus.view.atom":      "read",
    "thesaurus.view.curation":  "read",
    "thesaurus.view.series":    "read",
    # Weaver — constituent-word → protoword links (runs as JCL job under admin/client)
    # weave / weave_batch: nucleus writes — creates protowords, links to nucleus
    # weave_client: client cortex writes — links to existing nucleus protowords only,
    #               no data crosses the black-hole boundary into shared knowledge
    "sys.weaver.weave":         "write",
    "sys.weaver.weave_batch":   "write",
    "sys.weaver.weave_client":  "write",
    "sys.weaver.decompose":     "write",
    "sys.weaver.drain_pending": "write",
    # Link / alias remove
    "ln.rm": "drop",
    "al.rm": "drop",
    # Ref context
    "ref.get": "read",
    "ref.set": "write",
    # Log list
    "log.ls": "read",
    # Session focus
    "session.focus": "status",
    # Onto admin (handlers enforce role:librarian internally)
    "onto.genesis.redo":  "write",
    "onto.scope.drop":    "drop",
    # Auth / session (handlers enforce own-user / role:admin internally)
    "sys.passwd": "status",
    "sys.su":     "status",
    # User management — ADMIN-only capability (handlers also assert admin).
    # Mapping to the dedicated iam.manage capability (not the generic
    # write/read/drop that every USER holds) means a missing in-handler
    # _assert_admin can no longer become privilege escalation.
    "user.add":    "iam.manage",
    "user.id":     "iam.manage",
    "user.ls":     "iam.manage",
    "user.mod":    "iam.manage",
    "user.passwd": "iam.manage",
    "user.rm":     "iam.manage",
    # Group management
    "grp.new": "group.manage",
    "grp.add": "group.manage",
    "grp.del": "group.manage",
    "grp.lib": "group.manage",
    "grp.rm":  "group.manage",
    "grp.ls":  "read",
    # Dont — async messaging concept model
    "dont.create": "write",
    "dont.add":    "write",
    "dont.send":   "write",
    "dont.open":   "read",
    "dont.ls":     "read",
    # Survey concept model
    "survey.new":     "write",
    "survey.q.add":   "write",
    "survey.opt.add": "write",
    "survey.ls":      "read",
    "survey.list":    "read",
    "survey.open":    "read",
    "survey.ans":     "write",
    "survey.res.add": "write",
    "survey.rm":      "drop",
    # Geo concept model
    "geo.new":           "write",
    "geo.open":          "read",
    "geo.ls":            "read",
    "geo.map":           "read",
    "geo.rm":            "drop",
    "geo.clone":         "write",
    "geo.connect":       "write",
    "geo.place.add":     "write",
    "geo.place.state":   "write",
    "geo.coord.add":     "write",
    "geo.feature.add":   "write",
    "geo.layer.add":     "write",
    "geo.affine.add":    "write",
    "geo.event.add":     "write",
    "geo.observe.add":   "write",
    "geo.snapshot.add":  "write",
    "geo.transition.add":"write",
    "geo.time.rebuild":  "write",
    "geo.reveal":        "write",
    "geo.path":          "read",
    "geo.nearby":        "read",
    "geo.history":       "read",
    "geo.diagnose":      "read",
    # Homonoia concept model
    "homonoia.new":          "write",
    "homonoia.open":         "read",
    "homonoia.ls":           "read",
    "homonoia.map":          "read",
    "homonoia.rm":           "drop",
    "homonoia.district.add": "write",
    "homonoia.faction.add":  "write",
    "homonoia.law.add":      "write",
    "homonoia.event.add":    "write",
    "homonoia.profile":      "read",
    "homonoia.diagnose":     "read",
}
